### ISSUE TITLE
add error tracking

### ISSUE THREAD

**Issue by CharString** [open-formulieren/InferNoLogic#3]
Inspiration sources

 - [domdomegg/ottie](https://github.com/domdomegg/ottie/tree/master) by the author of the implementations of W and M that we're using.
 - [Explaining type inference — Duggan et al.](https://doi.org/10.1016/0167-6423(95)00007-0) for caveats of naively recording explanation paths
 - Possibly the Elm type checker; it's a simple language and it gives excellent actionable feedback on type errors.

Todo
- [ ] Treat partial applications e.g. `{"<": [1]}` as errors (see treatment of `{"var": []}`)
- [ ] Throw TypeError with helpful text and explanation data like paths in the expression so the location can be marked in the source text
- [ ] Error cases marked "TODO" in [test-d/tests.json](https://github.com/open-formulieren/InferNoLogic/blob/main/test-d/tests.json)
